image: node:lts

before_script:
  - echo "GITHUB_TOKEN=$GITHUB_TOKEN" > .env
  - rm -rf node_modules public dist
  - npm install

pages:
  script:
    - npm run build

  artifacts:
    paths:
      - public

  only:
    - main